#!/bin/bash
########################################################################
# prompt_colors ()
#	Remember that we need \[ and \] to escape sequences
#	when working within a prompt. So these are not the 
#	right vars for a simple `echo'. For those cases:
#
#	$ echo -e "\033[0;34 Whatever \033[0m"
#	or even
#	$ echo -e "\e[0;34 Whatever \e[0m"
# 
########################################################################

prompt_colors ()
{
	# List of colors to choose from and plug into template

	black="\[\033[0;30m\]"
	gray="\[\033[1;30m\]"
	red="\[\033[0;31m\]"
	light_red="\[\033[1;31m\]"
	green="\[\033[0;32m\]"
	light_green="\[\033[1;32m\]"
	brown="\[\033[0;33m\]"
	yellow="\[\033[1;33m\]"
	blue="\[\033[0;34m\]"
	light_blue="\[\033[1;34m\]"
	purple="\[\033[0;35m\]"
	pink="\[\033[1;35m\]"
	cyan="\[\033[0;36m\]"
	light_cyan="\[\033[1;36m\]"
	light_gray="\[\033[0;37m\]"
	white="\[\033[1;37m\]"

}
